[package]
name = "socket_test"
version = "0.1.0"
authors = ["awesomelemonade <awesomelemonade@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.3.12"
hex = "0.4"
